version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: compile PDFs 
          command: jupyter nbconvert --to html --output-dir='pdf' *.ipynb

