version: 2
jobs:
  build:
    docker: 
        - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
                sudo apt-get update
                sudo apt-get install texlive-xetex pandoc
                sudo pip install jupyter
      - run:
          name: compile PDFs 
          command: jupyter nbconvert --to pdf --output-dir='pdf' *.ipynb
      - store_artifacts:
          path: pdf/
          destination: pdf

